<template>
  <component :is="computedIcon" :class="[props.class]" :size="props.size" :stroke-width="strokeWidth" class="icon cursor-pointer transition-all duration-100"></component>
</template>
<script>
import {
  IconAdjustmentsAlt,
  IconArrowBack,
  IconArrowDown,
  IconArrowLeft,
  IconArrowRight,
  IconArrowRightCircle,
  IconArrowsExchange,
  IconArrowsLeftRight,
  IconArrowsSort,
  IconArrowUp,
  IconBell,
  IconBellCog,
  IconBook,
  IconBrandGoogleAnalytics,
  IconBuilding,
  IconCalendarCheck,
  IconCaretDownFilled,
  IconCaretUpDown,
  IconChartBarPopular,
  IconChartCandle,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconChevronsLeft,
  IconChevronsRight,
  IconDeviceMobileShare,
  IconCircle,
  IconCircleArrowRight,
  IconCircleCheck,
  IconCircleCheckFilled,
  IconCircleFilled,
  IconCircleMinus,
  IconCirclePlus,
  IconCircleX,
  IconCloudDownload,
  IconCode,
  IconCopy,
  IconCreditCard,
  IconDotsVertical,
  IconEqual,
  IconExchange,
  IconEye,
  IconEyeOff,
  IconGift,
  IconGridScan,
  IconHeartHandshake,
  IconHelp,
  IconHome,
  IconInfoCircle,
  IconLayoutGrid,
  IconLayoutSidebarLeftCollapseFilled,
  IconLoader,
  IconLoader3,
  IconMinus,
  IconPencil,
  IconPlus,
  IconPointFilled,
  IconPower,
  IconPuzzle,
  IconRefresh,
  IconRepeat,
  IconRotateClockwise,
  IconSearch,
  IconSettings,
  IconSquareRoundedXFilled,
  IconTable,
  IconTool,
  IconTrash,
  IconTrendingDown,
  IconTrendingUp,
  IconUser,
  IconUsersPlus,
  IconWallet,
  IconWorld,
  IconBuildingBank,
  IconX,
  IconRobot,
  IconMenu2,
  IconRosetteDiscountCheck,
  IconShieldCheckFilled,
  IconBan,
} from '@tabler/icons-vue'
import { computed, reactive } from 'vue'

const iconMap = {
  menu: IconMenu2,
  home: IconHome,
  filter: IconAdjustmentsAlt,
  tool: IconTool,
  copy: IconCopy,
  check: IconCheck,
  'circle-arrow-down-right': IconCircleArrowRight,
  'copy-2': IconGridScan,
  pencil: IconPencil,
  ban: IconBan,
  'arrow-exchange': IconArrowsExchange,
  'arrow-back': IconArrowBack,
  'arrow-left-right': IconArrowsLeftRight,
  grid: IconLayoutGrid,
  'chart-bar': IconChartBarPopular,
  code: IconCode,
  'bell-cog': IconBellCog,
  repeat: IconRepeat,
  analytics: IconBrandGoogleAnalytics,
  help: IconHelp,
  'caret-down': IconCaretDownFilled,
  table: IconTable,
  collapse: IconLayoutSidebarLeftCollapseFilled,
  sort: IconArrowsSort,
  'close-filled': IconSquareRoundedXFilled,
  loader: IconLoader,
  gift: IconGift,
  'arrow-right': IconArrowRight,
  'arrow-left': IconArrowLeft,
  'arrow-up': IconArrowUp,
  'arrow-down': IconArrowDown,
  'heart-handshake': IconHeartHandshake,
  'eye-off': IconEyeOff,
  eye: IconEye,
  book: IconBook,
  'credit-card': IconCreditCard,
  settings: IconSettings,
  'trending-up': IconTrendingUp,
  'trending-down': IconTrendingDown,
  download: IconCloudDownload,
  info: IconInfoCircle,
  dots: IconDotsVertical,
  'chart-candle': IconChartCandle,
  bell: IconBell,
  loading: IconLoader3,
  user: IconUser,
  search: IconSearch,
  minus: IconMinus,
  equal: IconEqual,
  'circle-plus': IconCirclePlus,
  'circle-rosette': IconRosetteDiscountCheck,
  'circle-minus': IconCircleMinus,
  'arrow-right-circle': IconArrowRightCircle,
  exchange: IconExchange,
  'circle-check': IconCircleCheck,
  'chev-left': IconChevronLeft,
  'chev-right': IconChevronRight,
  building: IconBuilding,
  'calendar-check': IconCalendarCheck,
  users: IconUsersPlus,
  wallet: IconWallet,
  'caret-up-down': IconCaretUpDown,
  'chevs-left': IconChevronsLeft,
  'chevs-right': IconChevronsRight,
  rotate: IconRotateClockwise,
  plus: IconPlus,
  'shield-check': IconShieldCheckFilled,
  puzzle: IconPuzzle,
  'circle-x': IconCircleX,
  refresh: IconRefresh,
  x: IconX,
  'circle-check-filled': IconCircleCheckFilled,
  'circle-filled': IconCircleFilled,
  '-': IconMinus,
  'arrows-sort': IconArrowsSort,
  circle: IconCircle,
  world: IconWorld,
  'point-filled': IconPointFilled,
  trash: IconTrash,
  power: IconPower,
  'device-mobile-share': IconDeviceMobileShare,
  bank: IconBuildingBank,
  robot: IconRobot,
}
const icons = Object.keys(iconMap)
</script>
<script setup>
const props = defineProps({
  class: String,
  size: Number,
  strokeWidth: Number,
  name: {
    type: String,
    validator: (value) => icons.includes(value),
  },
})

const data = reactive({
  icons: iconMap,
})

const computedIcon = computed(() => data.icons[props.name])

const isFilled = computed(() => props.name.includes('-filled'))
</script>
